### ISSUE TITLE
ncm-ceph: mon keyring when changing deploy host.

### ISSUE THREAD

**Issue by GRyall** [quattor/configuration-modules-core#592] opened 2015-09-28 16:35 UTC
We have just gone through the process of changing which host acts as our deploy host. This was relatively painless - we just changed the relevant value, sorted the ceph user private key and ran quattor. The one catch was that I had to copy /home/ceph/ceph.mon.keyring from the old deployhost to the new before we could deploy any new monitors successfully (otherwise the component generated a new one that then wouldn't work). Is this expected behaviour? It would be useful if it could look on the other mons for the keyring before generating a new one.

**Comment by kwaegema** [comment] 2015-09-30 14:46
Hmm, normally this should be done already in the component.. Maybe the component did run when the new deployhost could not connect to the monitors yet (so eg when the other hosts didn't had the deployhost in their authorized_keys) Then the default behaviour is to generate new config if there is not yet a ceph.mon.keyring.
If this is the case, I can see if I can further finetune this, but if the host can access at least one of the mons, it should be able to fetch the key from there already

**Comment by kwaegema** [comment] 2016-02-22 11:13
@GRyall : I should have put my comment more in a question-form :smile: DId you run the component when ALL the monitors weren't accessible (so probably because authorized_key not yet in place) . I ask this because then that would be the expected behaviour (this is how the config gets created on clean install) . If not, that should have worked, so then it could be a bug.

**Comment by GRyall** [comment] 2016-02-22 11:33
@kwaegema I think it is highly likely that the authorized_key was not in place.

**Comment by kwaegema** [comment] 2016-02-23 13:31
@GRyall If it's ok, I would close the issue then for now. Normally if the mons are accessible, it would copy the keyring. So once the mons are accessible, you can also delete the new files and it will automaticly get the old files. I hope that is enough for a non-frequent case? Of course, let me know if you need something more.

**Comment by GRyall** [comment] 2016-02-23 13:33
Seems reasonable enough to me.

**Closed** 2016-02-23 13:33 UTC
